# syntax=docker/dockerfile:1
# Victor-ray, S. <12261439+ZendaiOwl@users.noreply.github.com>
FROM debian:stable-slim
RUN apt-get update -y && apt-get install -y g++ make gawk wget curl binutils xz-utils tar zip bzip2 texinfo \
bison flex build-essential ncurses-base ncurses-term libncurses5-dev ncdu tty-clock colorize \
nano-tiny libtinfo6 libncursesw6 libncurses6 libncurses-dev rsync
